[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "atk",
  "cups",
  "libxshmfence",
  "libdrm",
  "libxrandr",
  "libxdamage",
  "libxcomposite",
  "libxkbcommon",
  "pango",
  "cairo",
  "alsaLib",
  "libXcursor",
  "libXext",
  "libXi",
  "libXtst",
  "libXScrnSaver",
  "libx11",
  "libxcb",
  "libxfixes",
  "expat",
  "fontconfig",
  "gtk3"
]
