[build]
builder = "heroku/buildpacks:20"

[start]
cmd = "node index.js"

[variables]
PORT = "8080"

[phases.setup]
nixPkgs = ["nodejs", "chromium", "nss", "atk", "cups", "libx11", "libxcomposite", "libxdamage", "libxrandr", "libxss", "libxtst", "mesa", "pango", "libdrm", "glib", "gtk3"]
