[phases.setup]
aptPkgs = [
  "libx11-xcb1",
  "libxcb-dri3-0",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm-dev",
  "libgtk-3-0",
  "libasound2",
  "libnss3",
  "libxss1",
  "libxtst6",
  "fonts-liberation",
  "xdg-utils",
  "wget",
  "ca-certificates"
]
